services:
  app:
    image: localhost/lab-fastify:latest
    build: .
    depends_on:
      - db
    volumes:
      - ./config:/app/config:Z
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: fastify
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: fastify
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

