on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: docker.io/library/node:20

    env:
      NODE_ENV: development

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm install && npm install -g webpack-cli

      - name: Run tests
        run: npm test -s
